name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Clean previous builds
        run: make fclean || true

      - name: Build with strict flags
        run: |
          make 

      - name: Check binary exists
        run: |
          if [ ! -f miniRT ] && [ ! -f RayTracer ]; then
            echo "Error: Binary not found after compilation"
            exit 1
          fi
